version: "3.8"

services:
  monolith:
    container_name: monolith
    hostname: monolith
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - '8080:8080'
      - '8085:8085'
    env_file:
      - docker/.env
    depends_on:
      - postgres
    command: [ "./wait-for", "postgres:5432", "--", "/mallbots/monolith" ]
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: itsasecret
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
      - './docker/database:/docker-entrypoint-initdb.d'
  pgadmin:
    image: dpage/pgadmin4
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: foobarbaz
    ports:
      - '9090:80'
    restart: unless-stopped

volumes:
  pgdata:
